### PR TITLE
Eclipse 4.4.x support and many other updates

### PR DESCRIPTION
**Pull request by hazendaz**
@mblanchette I had forked from google code some time ago.  I believe my fork was closest to your original and just bringing it up to date in many areas, making it reflect git now, and support for ecipse 4.4.x.  I've been running my original fork in a large environment for about 5 months and it is working as expected.  I realize this is a very huge pull request so if you want it to come in chunks please let me know.  I believe there are a number of things to to happen to get this where it needs to be which will come over time and much easier now this is in git.  For example, the test formatting options are still on older eclipse version.  I can update that in a subsequent pull and any other items that jump out.

Few other things, this is prepped for using travis ci, has badges for maven central and travis ci.  It attaches to OSS sonatype directly now since googlecode is now gone.  I suspect a few weeks and this could be released to central.

### CODE REVIEW

**Comment by hazendaz** [comment]
Forgot to mention.  Used git attributes so code has been normalized.  Diff listing is smart enough to show no real changes.  The changes in that case are line ending style.

**Comment by ctubbsii** [comment]
Any update on this? The PR has been open awhile, and would be nice to have in a new version.

**Comment by hazendaz** [comment]
What I can do personally is make my own copy available in maven central.  I don't fee as though I'm getting much love here.  I had posted on the issues over on google code a long time ago that I would take care of luna support.  I've done that and even one other person forked my project.  This now has been here for a month.  Obviously Mars is fast approaching so we need to get this out in some form.  I believe the apache licensing allows me freedom to do this.  So you tell me, would you want to pull this from me in maven central or continue to wait?  If you are willing to use my copy until original author catches up on this, then I will push and release this as quickly as possible as I soon will want to move to Mars and get to newer maven versions that now require java 7.

**Comment by mblanchette** [comment]
I think that you taking over this project and releasing to Maven central is fine.
I sadly don't have the time to maintain it currently.

**Comment by hazendaz** [comment]
Completely understandable!  I have less and less time on a daily basis these days but still try to get as much as possible moving.  Do you want to keep it with the same groupId, switch it over to com.github.*, or just have me release under my own groupId (com.github.hazendaz)?

**Comment by mblanchette** [comment]
I would switch the groupId to com.github._ and artifactId (per #38).
Releasing under your groupId is ok for me, especially if you will be deploying it (like Sonatype Nexus in past).

**Comment by ctubbsii** [comment]
Another option is to fork to transfer the repo to an organizational/group github account, and create a team on that, so that multiple people have commit access to the canonical repo. Transferring a repo to a group account also has the added benefit of github automatically redirecting traffic to the new location, and it retains the outstanding issues.

If you wish, I can volunteer the org account for my domain (revelc.net: http://github.com/revelc/), which I use for other random OSS projects (without any obligation to use my groupId).

**Comment by mblanchette** [comment]
I'd be fine transferring to your organization, just add me as an admin on a team.

**Comment by hazendaz** [comment]
@ctubbsii are you willing to give us both access?  Given there are other things out there, maybe not.  Other option is still to go this path as follows.

Organizations are free for open source.  @mblanchette, you could go into the configuration, create 'java-formatter-maven-plugin' organization.  I have a new PR switching over to this to align with that naming style also fixing issue #38.

At that point, would need @ctubbsii help on how to push this over there with project name change to 'java-formatter-maven-plugin'.

I'd also say we invite https://github.com/velo over there as he branched off this project long ago.  While there are some commonalities, his is vastly different now.  His also sufferes from maven naming violation but has changed enough that he simply calls it the 'maven-formatter-plugin'.  Maybe he would be willing to pull that into the fold then we can work at potentially bringing those two together over time.  So haven't a single place to do this would work out great.

Releasing to central is no problem.  We just need to have sonatype access to release.  That is a simple process and could be live within a day or two.

**Comment by ctubbsii** [comment]
Yes, I'd be willing to give anybody access. If it helps, I also have
net.revelc.* groupId set up for Central sync. Creating a new org is an
option, too. I can't do much until Monday, though.

**Comment by hazendaz** [comment]
I'm good using yours.  Doesn't matter much to me.

I've requested to be granted access to sonatype on ticket
https://issues.sonatype.org/browse/OSSRH-15142

Can you comment on that ticket to grant me access?

**Comment by hazendaz** [comment]
Also, can you add me to your organization?

**Comment by ctubbsii** [comment]
I added you both to the organization, so you should be able to transfer the project there, and administer it.

**Comment by hazendaz** [comment]
Thanks

--- Original Message ---

**Comment by ctubbsii** [comment]
As far as I can tell, everything is set up. You just need to accept the invitation to the organization, and then @mblanchette  should be able to transfer the project to @revelc. One can do this in the repository settings, near the bottom. I think the invitation to the organization has to be accepted first, if my understanding of [this page][1] is correct.

More details about transferring repos are [here][2].

[1]: https://help.github.com/articles/permission-levels-for-an-organization-repository/
[2]: https://help.github.com/articles/transferring-a-repository/

**Comment by mblanchette** [comment]
Project has been transferred

**Comment by ctubbsii** [comment]
Okay, I'll add a link to the front page of http://code.revelc.net / http://revelc.github.io/ .
I'll also go ahead and rename the repo to "formatter-maven-plugin" (GitHub will continue to redirect from the old location).

**Pull request merged**
